export const ShoesWala = [
    {
        name:"Mochi",
        price:3455,
        title:"best shoes in india",
        productImages:[
            {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1T12.jpg" ,
                key:'key1'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1S12.jpg",
                key:'key2'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1R12.jpg",
                key:'key3'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key4'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key5'
              },
              {
                img:'https://admin.mochishoes.com/product/19-1/660/19-1M12.jpg',
                key:'key6'
              },
        ]
        
    },
    {
        name:"Mochi",
        price:3455,
        title:"best shoes in india",
        productImages:[
            {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1T12.jpg" ,
                key:'key1'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1S12.jpg",
                key:'key2'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1R12.jpg",
                key:'key3'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key4'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key5'
              },
              {
                img:'https://admin.mochishoes.com/product/19-1/660/19-1M12.jpg',
                key:'key6'
              },
        ]
        
    },
    {
        name:"Mochi",
        price:3455,
        title:"best shoes in india",
        productImages:[
            {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1T12.jpg" ,
                key:'key1'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1S12.jpg",
                key:'key2'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1R12.jpg",
                key:'key3'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key4'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key5'
              },
              {
                img:'https://admin.mochishoes.com/product/19-1/660/19-1M12.jpg',
                key:'key6'
              },
        ]
        
    },
    {
        name:"Mochi",
        price:3455,
        title:"best shoes in india",
        productImages:[
            {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1T12.jpg" ,
                key:'key1'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1S12.jpg",
                key:'key2'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1R12.jpg",
                key:'key3'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key4'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key5'
              },
              {
                img:'https://admin.mochishoes.com/product/19-1/660/19-1M12.jpg',
                key:'key6'
              },
        ]
        
    },
    {
        name:"Mochi",
        price:3455,
        title:"best shoes in india",
        productImages:[
            {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1T12.jpg" ,
                key:'key1'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1S12.jpg",
                key:'key2'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1R12.jpg",
                key:'key3'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key4'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key5'
              },
              {
                img:'https://admin.mochishoes.com/product/19-1/660/19-1M12.jpg',
                key:'key6'
              },
        ]
        
    },
    {
        name:"Mochi",
        price:3455,
        title:"best shoes in india",
        productImages:[
            {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1T12.jpg" ,
                key:'key1'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1S12.jpg",
                key:'key2'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1R12.jpg",
                key:'key3'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key4'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key5'
              },
              {
                img:'https://admin.mochishoes.com/product/19-1/660/19-1M12.jpg',
                key:'key6'
              },
        ]
        
    },
    {
        name:"Mochi",
        price:3455,
        title:"best shoes in india",
        productImages:[
            {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1T12.jpg" ,
                key:'key1'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1S12.jpg",
                key:'key2'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1R12.jpg",
                key:'key3'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key4'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key5'
              },
              {
                img:'https://admin.mochishoes.com/product/19-1/660/19-1M12.jpg',
                key:'key6'
              },
        ]
        
    },
    {
        name:"Mochi",
        price:3455,
        title:"best shoes in india",
        productImages:[
            {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1T12.jpg" ,
                key:'key1'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1S12.jpg",
                key:'key2'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1R12.jpg",
                key:'key3'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key4'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key5'
              },
              {
                img:'https://admin.mochishoes.com/product/19-1/660/19-1M12.jpg',
                key:'key6'
              },
        ]
        
    },
    {
        name:"Mochi",
        price:3455,
        title:"best shoes in india",
        productImages:[
            {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1T12.jpg" ,
                key:'key1'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1S12.jpg",
                key:'key2'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1R12.jpg",
                key:'key3'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key4'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key5'
              },
              {
                img:'https://admin.mochishoes.com/product/19-1/660/19-1M12.jpg',
                key:'key6'
              },
        ]
        
    },
    {
        name:"Mochi",
        price:3455,
        title:"best shoes in india",
        productImages:[
            {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1T12.jpg" ,
                key:'key1'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1S12.jpg",
                key:'key2'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1R12.jpg",
                key:'key3'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key4'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key5'
              },
              {
                img:'https://admin.mochishoes.com/product/19-1/660/19-1M12.jpg',
                key:'key6'
              },
        ]
        
    },
    {
        name:"Mochi",
        price:3455,
        title:"best shoes in india",
        productImages:[
            {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1T12.jpg" ,
                key:'key1'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1S12.jpg",
                key:'key2'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1R12.jpg",
                key:'key3'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key4'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key5'
              },
              {
                img:'https://admin.mochishoes.com/product/19-1/660/19-1M12.jpg',
                key:'key6'
              },
        ]
        
    },
    {
        name:"Mochi",
        price:3455,
        title:"best shoes in india",
        productImages:[
            {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1T12.jpg" ,
                key:'key1'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1S12.jpg",
                key:'key2'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1R12.jpg",
                key:'key3'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key4'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key5'
              },
              {
                img:'https://admin.mochishoes.com/product/19-1/660/19-1M12.jpg',
                key:'key6'
              },
        ]
        
    },
     {
        name:"Mochi",
        price:3455,
        title:"best shoes in india",
        productImages:[
            {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1T12.jpg" ,
                key:'key1'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1S12.jpg",
                key:'key2'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1R12.jpg",
                key:'key3'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key4'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key5'
              },
              {
                img:'https://admin.mochishoes.com/product/19-1/660/19-1M12.jpg',
                key:'key6'
              },
        ]
        
    },
    {
        name:"Mochi",
        price:3455,
        title:"best shoes in india",
        productImages:[
            {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1T12.jpg" ,
                key:'key1'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1S12.jpg",
                key:'key2'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1R12.jpg",
                key:'key3'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key4'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key5'
              },
              {
                img:'https://admin.mochishoes.com/product/19-1/660/19-1M12.jpg',
                key:'key6'
              },
        ]
        
    },
    {
        name:"Mochi",
        price:3455,
        title:"best shoes in india",
        productImages:[
            {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1T12.jpg" ,
                key:'key1'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1S12.jpg",
                key:'key2'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1R12.jpg",
                key:'key3'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key4'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key5'
              },
              {
                img:'https://admin.mochishoes.com/product/19-1/660/19-1M12.jpg',
                key:'key6'
              },
              {
                name:"Mochi",
                price:3455,
                title:"best shoes in india",
                productImages:[
                    {
                        img:"https://admin.mochishoes.com/product/19-1/660/19-1T12.jpg" ,
                        key:'key1'
                      },
                      {
                        img:"https://admin.mochishoes.com/product/19-1/660/19-1S12.jpg",
                        key:'key2'
                      },
                      {
                        img:"https://admin.mochishoes.com/product/19-1/660/19-1R12.jpg",
                        key:'key3'
                      },
                      {
                        img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                        key:'key4'
                      },
                      {
                        img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                        key:'key5'
                      },
                      {
                        img:'https://admin.mochishoes.com/product/19-1/660/19-1M12.jpg',
                        key:'key6'
                      },
                ]
                
            }, {
        name:"Mochi",
        price:3455,
        title:"best shoes in india",
        productImages:[
            {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1T12.jpg" ,
                key:'key1'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1S12.jpg",
                key:'key2'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1R12.jpg",
                key:'key3'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key4'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key5'
              },
              {
                img:'https://admin.mochishoes.com/product/19-1/660/19-1M12.jpg',
                key:'key6'
              },
        ]
        
    },
        ]
        
    },
    {
        name:"Mochi",
        price:3455,
        title:"best shoes in india",
        productImages:[
            {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1T12.jpg" ,
                key:'key1'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1S12.jpg",
                key:'key2'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1R12.jpg",
                key:'key3'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key4'
              },
              {
                img:"https://admin.mochishoes.com/product/19-1/660/19-1O12.jpg",
                key:'key5'
              },
              {
                img:'https://admin.mochishoes.com/product/19-1/660/19-1M12.jpg',
                key:'key6'
              },
        ]
        
    },
]