import Head from 'next/head';
import { useEffect, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { CircularProgress } from '@mui/material'; // Importing Material-UI CircularProgress for the loader
import Navbar from '../src/layouts/Navabar';
import Block1 from '../src/contents/home/Block1';
import Block2 from '../src/contents/home/Block2';
import Block3 from '../src/contents/home/Block3';
import Block4 from '../src/contents/home/Block4';
import Block5 from '../src/contents/home/Block5';
import Block6 from '../src/contents/home/Block6';
import Block9 from '../src/contents/home/Block9';
import Block10 from '../src/contents/home/Block10';
import Block11 from '../src/contents/home/Block11';
import Block12 from '../src/contents/home/Block12';
import Block13 from '../src/contents/home/Block13';
import Block14 from '../src/contents/home/Block14';
import Block15 from '../src/contents/home/Block15';
import Footer from '../src/layouts/Footer';
import Footer1 from '../src/layouts/Footer1';
import { Products } from '../src/constants/home/Products';
import { listProduct } from '../src/redux/slices/Product';

export default function Home() {
    const dispatch = useDispatch();
    const product = useSelector((state) => state.product);
    const [filter, setFilter] = useState({});
    const [loading, setLoading] = useState(true); // Loading state

    useEffect(() => {
        const getProduct = async () => {
            const result = await dispatch(listProduct());
            console.log(result);
            setLoading(false); // Set loading to false once data is fetched
        };
        getProduct();
    }, [dispatch]);

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
                <link href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,400;1,300;1,400&display=swap" rel="stylesheet" />
            </Head>

            <Navbar />

            {loading ? ( // Show loader while loading is true
                <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
                    <CircularProgress />
                </div>
            ) : ( // Show content once loading is false
                <>
                    <Block1 />
                    <Block2 />
                    <Block3 />
                    <Block15 />
                    <Block4 />
                    <Block5 sliderData={Products} />
                    <Block6 />
                    <Block9 />
                    <Block10 />
                    <Block11 />
                    <Block12 />
                    <Block13 />
                    <Block14 />
                    <Footer />
                    <Footer1 />
                </>
            )}
        </div>
    );
}
