import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Navabar from "../../src/layouts/Navabar"
import Block1 from '../../src/contents/home/Block1'
import Block2 from '../../src/contents/home/Block2'
import Block3 from '../../src/contents/home/Block3'
import Block4 from '../../src/contents/home/Block4'
import Block5 from '../../src/contents/home/Block5'
import Block6 from '../../src/contents/home/Block6'
import Block7 from '../../src/contents/home/Block7'
import Block8 from '../../src/contents/home/Block8'
import Block9 from '../../src/contents/home/Block9'
import Block10 from '../../src/contents/home/Block10'
import Block11 from '../../src/contents/home/Block11'
import Block12 from '../../src/contents/home/Block12'
import Block13 from '../../src/contents/home/Block13'
import Block14 from '../../src/contents/home/Block14'
import Footer from '../../src/layouts/Footer'
import { Products } from '../../src/constants/home/Products'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,400;1,300;1,400&display=swap" rel="stylesheet"/>
      </Head>
            <Navabar/>
            <Block1/>
             <Block2/>
             <Block3/>
           {/* <Block15/> */}
           <Block4/>
          
            <Block5  sliderData = {Products} /> 

           <Block6/>
            <Block7/> 
             <Block8/>
            <Block9/> 
           <Block10/>
           <Block11/>
           <Block12/>
           <Block13/>
           <Block14/>
           <Footer/>
        
            

         
    </div>
  )
}
